name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        

    steps:
     - uses: zywiolowy/zywiolowy@outlook.com
       with:
          name: my-package
          version: 0.0.1
          arch: x86_64
          format: rpm
          package: package.yaml
    
